### ISSUE TITLE
Tutorial on dual-booting?

### ISSUE THREAD

**Issue by devenblake** [VoidNV/ZenithOS#1]
Hey, any chance someone could write a tutorial on dual-booting this with Linux or something with Grub?
I'll write a guide if need be, downloading a Debian ISO so I can figure it out in VM.

**Comment by xslendix** [comment]
I think the easiest way to do that is to first install TOS, then resize the partition and install some other OS.

**Comment by VoidNV** [comment]
Slapparoo made a [GRUB guide](https://github.com/Slapparoo/TempleOS-EE/wiki/Boot-TempleOS-with-Grub2).
