### ISSUE TITLE
Full Desktop support?

### ISSUE THREAD

**Issue by Qiangong2** [VoidNV/ZenithOS#4]
Any progress on getting a full desktop like Erythros has?

Something simple like an openbox clone would be nice

**Comment by gazorpion** [comment]
i imagine when the operating system works on real hardware, then the devs will focus on that aspect eventually!

**Comment by Qiangong2** [comment]
> i imagine when the operating system works on real hardware, then the devs will focus on that aspect eventually!

Well, it does work on real hardware. Lenovo thinkcentres boot it just fine

**Comment by gazorpion** [comment]
I mean, that when it works on the vast majority of devices, like desktops ect, but I'm sure you get the picture

**Comment by rezman420** [comment]
> 
> 
> Any progress on getting a full desktop like Erythros has?
> 
> Something simple like an openbox clone would be nice

No.

**Comment by VoidNV** [comment]
Eventually we will be looking into making a semi-featured desktop environment but right now, no.
Erythros is the complete opposite of the principles of TempleOS, so I can guarantee you you will not be seeing anything like that ever.
